#!/bin/bash
# Script to check GitHub Actions deployment status

echo "=== GitHub Actions Deployment Status Checker ==="
echo ""
echo "To check GitHub Actions status, you can:"
echo ""
echo "1. Via GitHub Web Interface:"
echo "   - Go to: https://github.com/pbertain/sportspuff-v6/actions"
echo "   - Look for recent workflow runs for 'dev' and 'main' branches"
echo "   - Check if deployments succeeded (green checkmark) or failed (red X)"
echo ""
echo "2. Via GitHub CLI (if installed):"
echo "   gh run list --branch dev --limit 5"
echo "   gh run list --branch main --limit 5"
echo ""
echo "3. Check recent deployments:"
echo "   - Dev branch deployments should show 'deploy-dev' job"
echo "   - Main branch deployments should show 'deploy-prod' job"
echo ""
echo "4. Check for failed runs:"
echo "   - Look for any red X marks indicating failures"
echo "   - Click on failed runs to see error messages"
echo ""
echo "=== Current Branch Info ==="
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
echo "Current branch: $CURRENT_BRANCH"
echo ""
echo "=== Recent Commits ==="
git log --oneline -5 --all 2>/dev/null | head -5 || echo "Could not fetch git log"
echo ""
echo "=== Branch Comparison ==="
echo "To see differences between main and dev:"
echo "  git log main..dev --oneline  # commits in dev not in main"
echo "  git log dev..main --oneline  # commits in main not in dev"

