---
# Create systemd service file
- name: Create systemd service file
  template:
    src: sportspuff.service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: '0644'
  notify: "reload systemd"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start service
  systemd:
    name: "{{ service_name }}"
    enabled: yes
    state: started
