---
# Main playbook for sportspuff-v6 deployment

- name: Deploy sportspuff-v6 application
  hosts: "{{ target_env | default('dev') }}"
  become: yes
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/{{ target_env | default('dev') }}.yml
  
  roles:
    - ../roles/sportspuff-app
    - ../roles/systemd-service
  
  handlers:
    - name: restart sportspuff service
      systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: yes
      notify: "restart sportspuff service"
