name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
        
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > ~/.ssh/nirdclub_id_ed25519
        chmod 600 ~/.ssh/nirdclub_id_ed25519
        ssh-keyscan -H host74.nird.club >> ~/.ssh/known_hosts
        
    - name: Deploy to production
      run: |
        ansible-playbook \
          -i ansible/inventory \
          -u ansible \
          --private-key ~/.ssh/nirdclub_id_ed25519 \
          ansible/playbooks/deploy.yml \
          -e target_env=prod
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
